const SUPABASE_URL='https://kahbxvbirsjmednkybse.supabase.co';
const SUPABASE_KEY='sb_publishable_L1TY-QEyFsWDeDRy_saOUQ_GP8TjADm';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
window.veronzaSupabase=sb;
let orders=[],filter='all',selected=null,urlOrderHandled=false;
const $=s=>document.querySelector(s);
const statusNames={pending:'قيد المراجعة',confirmed:'تم التأكيد',preparing:'قيد التجهيز',shipped:'جاري التوصيل',delivered:'تم التسليم',cancelled:'ملغي',returned:'مرتجع'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function showApp(session){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#adminEmail').textContent=session.user.email||''}
function showLogin(){$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
async function checkAdmin(token){
  const r=await fetch('/api/admin-auth',{headers:{Authorization:`Bearer ${token}`}});
  let data={};
  try{data=await r.json()}catch(_){}
  if(!r.ok||data.ok!==true){
    return {ok:false,status:r.status,error:data.error||'لا يوجد نص خطأ من السيرفر',debug:JSON.stringify(data)};
  }
  return {ok:true};
}
async function api(path,options={}){const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('انتهت جلسة الدخول');const r=await fetch(path,{...options,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',...(options.headers||{})}});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||'تعذر تنفيذ العملية');return body}
async function load(){try{const body=await api('/api/admin-orders');orders=body.orders||[];render();$('#lastUpdated').textContent='آخر تحديث '+new Date().toLocaleTimeString('ar-LY',{hour:'2-digit',minute:'2-digit'});maybeOpenFromUrl()}catch(e){toast(e.message)}}
function maybeOpenFromUrl(){if(urlOrderHandled)return;const id=new URLSearchParams(location.search).get('order');if(id&&orders.find(o=>o.id===id)){urlOrderHandled=true;openOrder(id)}}
function renderStats(){const c=s=>orders.filter(o=>o.status===s).length;$('#stats').innerHTML=[['كل الطلبات',orders.length],['جديدة',c('pending')],['قيد التجهيز',c('preparing')],['جاري التوصيل',c('shipped')],['تم التسليم',c('delivered')]].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}
function render(){renderStats();const list=filter==='all'?orders:orders.filter(o=>o.status===filter);const box=$('#orders');if(!list.length){box.innerHTML='<div class="empty">لا توجد طلبات في هذا القسم حالياً.</div>';return}box.innerHTML=list.map(o=>`<div class="order-row" data-open="${o.id}"><div class="order-number">${esc(o.order_number)}</div><div class="customer"><b>${esc(o.customer_name)}</b><small>${esc(o.customer_phone)}</small></div><div class="amount">${Number(o.total||0).toLocaleString('ar-LY')} د.ل</div><div><span class="status ${esc(o.status)}">${statusNames[o.status]||esc(o.status)}</span></div><div class="date">${new Date(o.created_at).toLocaleString('ar-LY')}</div><button class="details-btn" data-open="${o.id}">التفاصيل</button></div>`).join('')}
async function openOrder(id){selected=orders.find(o=>o.id===id);if(!selected)return;try{const body=await api('/api/admin-orders?order_id='+encodeURIComponent(id));selected={...selected,items:body.items||[]}}catch(e){toast(e.message);return}
$('#orderDetails').innerHTML=`<div class="detail-title"><span class="eyebrow">VERONZA ORDER</span><h2>${esc(selected.order_number)}</h2><p>${new Date(selected.created_at).toLocaleString('ar-LY')} · WhatsApp: ${esc(selected.whatsapp_status||'pending')}</p></div><div class="customer-box"><h3>بيانات الزبون</h3><div class="customer-grid"><div class="field"><b>الاسم</b><span>${esc(selected.customer_name)}</span></div><div class="field"><b>الهاتف</b><span>${esc(selected.customer_phone)}</span></div><div class="field" style="grid-column:1/-1"><b>العنوان</b><span>${esc(selected.customer_address)}</span></div></div><div class="contact-actions"><a href="tel:${esc(selected.customer_phone)}">اتصال بالزبون</a><a target="_blank" rel="noopener noreferrer" href="https://wa.me/${encodeURIComponent(selected.customer_phone.replace(/\D/g,''))}">WhatsApp</a></div></div><div class="items-box"><h3>المنتجات</h3>${selected.items.map(i=>`<div class="item">${i.image_url?`<img src="${esc(i.image_url)}" alt="">`:'<div></div>'}<div><div class="item-name">${esc(i.product_name)}</div><div class="item-meta">الكود: ${esc(i.product_code)} · اللون: ${esc(i.color||'—')} · المقاس: ${esc(i.size||'—')} · الكمية: ${esc(i.quantity)}</div></div><div class="item-price">${Number(i.unit_price||0).toLocaleString('ar-LY')} د.ل</div></div>`).join('')||'<div class="empty">لا توجد منتجات.</div>'}<div style="display:flex;justify-content:space-between;margin-top:12px;font-weight:800"><span>الإجمالي</span><span>${Number(selected.total||0).toLocaleString('ar-LY')} د.ل</span></div></div><div class="actions-box"><h3>إدارة الطلب</h3><div class="detail-actions"><select id="orderStatus">${Object.entries(statusNames).map(([k,v])=>`<option value="${k}" ${selected.status===k?'selected':''}>${v}</option>`).join('')}</select><div></div><textarea id="adminNote" placeholder="ملاحظات الأدمن">${esc(selected.admin_notes||'')}</textarea><button class="save-status" id="saveOrder">حفظ حالة الطلب</button></div></div>`;$('#orderModal').classList.remove('hidden');$('#saveOrder').onclick=saveOrder}
async function saveOrder(){try{const status=$('#orderStatus').value;const admin_notes=$('#adminNote').value;const body=await api('/api/admin-orders',{method:'PATCH',body:JSON.stringify({id:selected.id,status,admin_notes})});selected={...selected,...body.order};const idx=orders.findIndex(o=>o.id===selected.id);if(idx>=0)orders[idx]=selected;render();$('#orderModal').classList.add('hidden');if(body.notify){toast(body.notify.sent?'تم حفظ الطلب وإشعار الزبون عبر واتساب ✓':'تم حفظ الطلب، لكن إشعار الزبون بواتساب فشل')}else{toast('تم حفظ الطلب')}}catch(e){toast(e.message)}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const {data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#loginError').textContent=error.message;return}const adminCheck=await checkAdmin(data.session.access_token);if(!adminCheck.ok){await sb.auth.signOut();$('#loginError').textContent=`[تشخيص] ${adminCheck.debug}`;return}showApp(data.session);load()});
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();showLogin()};$('#refreshBtn').onclick=load;
$('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;filter=b.dataset.status;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===b));render()});$('#orders').addEventListener('click',e=>{const row=e.target.closest('[data-open]');if(row)openOrder(row.dataset.open)});$('#closeModal').onclick=()=>$('#orderModal').classList.add('hidden');$('#orderModal').addEventListener('click',e=>{if(e.target.id==='orderModal')e.currentTarget.classList.add('hidden')});
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session){const adminCheck=await checkAdmin(session.access_token);if(adminCheck.ok){showApp(session);load()}else{await sb.auth.signOut();showLogin()}}else{showLogin()}})();
setInterval(()=>{if(!$('#appView').classList.contains('hidden'))load()},30000);
