const WHATSAPP='218944000974';
const products=[
 {id:1,code:'VZ-BAG-001',name:'شنطة Veronza الفاخرة',price:450,type:'bags',img:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85',rating:'4.9',reviews:12,colors:['أسود','بيج','بني'],sizes:['موحد']},
 {id:2,code:'VZ-SHOE-002',name:'حذاء Veronza الأنيق',price:365,type:'shoes',img:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85',rating:'4.8',reviews:20,colors:['أبيض','أسود','بيج'],sizes:['37','38','39','40','41']},
 {id:3,code:'VZ-SET-003',name:'سيت كامل — شنطة + حذاء',price:699,type:'set',img:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85',extraImg:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85',rating:'5.0',reviews:8,colors:['أسود','بيج','بني'],sizes:['37','38','39','40','41']}
];
let cart=JSON.parse(localStorage.getItem('veronza-cart')||'[]');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(n){return `${n.toLocaleString('ar-LY')} د.ل`}
function productVisual(p){return p.extraImg?`<div class="set-visual"><img src="${p.img}" alt="${p.name} — الشنطة" loading="lazy"><img src="${p.extraImg}" alt="${p.name} — الحذاء" loading="lazy"></div>`:`<img src="${p.img}" alt="${p.name}" loading="lazy">`}
function optionMarkup(p){return `<div class="product-options"><label>اللون<select data-color="${p.id}">${p.colors.map((c,i)=>`<option value="${c}"${i===0?' selected':''}>${c}</option>`).join('')}</select></label><label>${p.type==='bags'?'المقاس':'المقاس'}<select data-size="${p.id}">${p.sizes.map((s,i)=>`<option value="${s}"${i===0?' selected':''}>${s}</option>`).join('')}</select></label></div>`}
function renderProducts(list=products){const grid=$('#productGrid');if(!grid)return;grid.innerHTML=list.map(p=>`<article class="product"><div class="product-img">${productVisual(p)}<button class="heart" aria-label="إضافة للمفضلة">♡</button>${p.type==='set'?'<span class="set-badge">سيت كامل</span>':''}</div><div class="product-info"><div class="product-name">${p.name}</div><div class="price">${money(p.price)}</div><div class="stars">★★★★★ <span>(${p.reviews})</span></div>${optionMarkup(p)}<button class="add" data-add="${p.id}">أضف إلى السلة　♧</button></div></article>`).join('');$$('[data-add]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.add);const p=products.find(x=>x.id===id);const color=$(`[data-color="${id}"]`).value;const size=$(`[data-size="${id}"]`).value;addToCart(id,color,size)}))}
function save(){localStorage.setItem('veronza-cart',JSON.stringify(cart))}
function addToCart(id,color,size){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id&&x.color===color&&x.size===size);item?item.qty++:cart.push({...p,qty:1,color,size});save();renderCart();openCart()}
function renderCart(){const box=$('[data-cart-items]'),count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.price*x.qty,0);$('[data-cart-total]').textContent=money(total);$('.bag span').textContent=count;box.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row" style="display:flex;gap:10px;align-items:center;margin-bottom:14px"><img src="${x.img}" style="width:64px;height:64px;object-fit:cover;background:#f5f2ed"><div style="flex:1"><strong style="font-size:12px">${x.name}</strong><div style="font-size:11px;color:#777">الكود: ${x.code}</div><div style="font-size:11px;color:#777">اللون: ${x.color} · المقاس: ${x.size}</div><div style="font-size:11px;color:#777">${money(x.price)} × ${x.qty}</div></div><button data-remove="${i}" style="border:0;background:none;font-size:20px">×</button></div>`).join(''):'<p style="color:#888;text-align:center">السلة فارغة حالياً.</p>';
$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);save();renderCart()})}
function openLayer(el){el.classList.add('open');$('.overlay').classList.add('show')}
function closeLayers(){$$('.mobile-menu,.search-panel,.cart-drawer').forEach(x=>x.classList.remove('open'));$('.overlay').classList.remove('show')}
function openCart(){closeLayers();openLayer($('[data-cart-drawer]'))}
function whatsappMessage(customer){const lines=cart.map(x=>`• ${x.name}\n  الكود: ${x.code}\n  اللون: ${x.color}\n  المقاس: ${x.size}\n  الكمية: ${x.qty}\n  السعر: ${money(x.price*x.qty)}\n  الصورة: ${x.img}`),total=cart.reduce((s,x)=>s+x.price*x.qty,0);return `السلام عليكم، نبي نطلب من Veronza Boutique\n\n${lines.join('\n\n')}\n\nالإجمالي: ${money(total)}\n\nبيانات الزبون:\nالاسم: ${customer.name}\nرقم الهاتف: ${customer.phone}\nالعنوان: ${customer.address}\n\nنبي نكمل تفاصيل الطلب والتوصيل عبر واتساب.`}
function openWhatsApp(message){window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
function openCheckout(){if(!cart.length){alert('أضف منتجاً إلى السلة أولاً.');return}const modal=$('[data-checkout-modal]');if(modal)modal.classList.add('open')}
function closeCheckout(){$('[data-checkout-modal]')?.classList.remove('open')}
$('[data-menu]').onclick=()=>openLayer($('[data-mobile-menu]'));$('[data-menu-close]').onclick=closeLayers;$('[data-overlay]').onclick=closeLayers;$('[data-cart]').onclick=openCart;$('[data-cart-close]').onclick=closeLayers;$('[data-search]').onclick=()=>{openLayer($('[data-search-panel]'));setTimeout(()=>$('#searchInput').focus(),250)};$('[data-search-close]').onclick=closeLayers;
$('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim(),results=$('#searchResults');if(!q){results.innerHTML='';return}const matches=products.filter(p=>p.name.includes(q));results.innerHTML=matches.length?matches.map(p=>`<div style="display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid #eee"><img src="${p.img}" style="width:55px;height:55px;object-fit:cover"><div><strong>${p.name}</strong><div>${money(p.price)}</div></div></div>`).join(''):'<p>لا توجد نتائج مطابقة.</p>'});
$$('.tabs button').forEach(btn=>btn.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const text=btn.textContent.trim();renderProducts(text==='الكل'?products:text==='الأحذية'?products.filter(p=>p.type==='shoes'):text==='الشنط'?products.filter(p=>p.type==='bags'):products.filter(p=>p.type==='set'))});
$('[data-newsletter]').onsubmit=e=>{e.preventDefault();const message=e.currentTarget.querySelector('input').value.trim();if(message)openWhatsApp(`السلام عليكم، نبي نتواصل مع Veronza Boutique.\nرسالتي: ${message}`);e.currentTarget.querySelector('input').value='';};
$('[data-checkout]').onclick=openCheckout;
$('[data-checkout-close]').onclick=closeCheckout;
$('[data-checkout-form]').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;const customer={name:form.querySelector('[name="name"]').value.trim(),phone:form.querySelector('[name="phone"]').value.trim(),address:form.querySelector('[name="address"]').value.trim()};if(!customer.name||!customer.phone||!customer.address){alert('لازم تكتب الاسم ورقم الهاتف والعنوان.');return}closeCheckout();openWhatsApp(whatsappMessage(customer));};
$('.whatsapp').onclick=()=>openWhatsApp('السلام عليكم، نبي نستفسر عن منتجات Veronza Boutique.');
$$('[data-whatsapp-link]').forEach(a=>a.onclick=e=>{e.preventDefault();openWhatsApp('السلام عليكم، نبي نتواصل مع Veronza Boutique.');});
$$('.footer-links a').forEach(a=>{if(a.textContent.includes('اتصل بنا'))a.onclick=e=>{e.preventDefault();openWhatsApp('السلام عليكم، نبي نتواصل مع Veronza Boutique.')}});
renderProducts();renderCart();