(()=>{
  const wait=()=>window.veronzaSupabase?init(window.veronzaSupabase):setTimeout(wait,300);
  const init=async(client)=>{
    const {data:{session}}=await client.auth.getSession(); if(!session)return;
    const {data:admin}=await client.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle(); if(!admin)return;
    if(!document.getElementById('vz-notify-style')){const s=document.createElement('style');s.id='vz-notify-style';s.textContent=`#vz-notify{position:relative}.vz-badge{position:absolute;top:1px;right:1px;background:#b21f2d;color:#fff;border-radius:99px;min-width:17px;height:17px;font:700 10px/17px Arial;text-align:center}.vz-panel{position:fixed;inset:0 0 0 auto;width:min(94vw,390px);background:#fff;z-index:180;box-shadow:-10px 0 35px #0002;transform:translateX(105%);transition:.25s;display:flex;flex-direction:column}.vz-panel.open{transform:none}.vz-nhead{display:flex;align-items:center;justify-content:space-between;padding:18px;border-bottom:1px solid #eee}.vz-nhead h3{margin:0}.vz-nhead button,.vz-enable{border:0;background:#111;color:#fff;border-radius:10px;padding:9px 12px;font:inherit}.vz-list{overflow:auto;padding:12px}.vz-item{border:1px solid #e8e3dc;border-radius:13px;padding:12px;margin-bottom:10px;cursor:pointer}.vz-item.unread{border-color:#111;background:#faf9f7}.vz-item strong{display:block}.vz-item small{display:block;color:#777;margin-top:5px}.vz-empty{padding:30px 12px;text-align:center;color:#777}.vz-shade{position:fixed;inset:0;background:#0006;z-index:175;display:none}.vz-shade.open{display:block}@media(min-width:700px){.vz-shade.open{display:none}}`;document.head.appendChild(s)}
    const btn=document.createElement('button');btn.id='vz-notify';btn.className='icon-btn';btn.type='button';btn.setAttribute('aria-label','الإشعارات');btn.innerHTML='🔔';document.querySelector('.header-actions')?.prepend(btn); if(!btn.isConnected)return;
    const badge=document.createElement('span');badge.className='vz-badge';badge.hidden=true;btn.appendChild(badge);
    const shade=document.createElement('div');shade.className='vz-shade';document.body.appendChild(shade); const panel=document.createElement('aside');panel.className='vz-panel';panel.innerHTML=`<div class="vz-nhead"><h3>الإشعارات</h3><button type="button" data-nclose>×</button></div><div style="padding:12px;border-bottom:1px solid #eee"><button class="vz-enable" type="button" data-enable>تفعيل إشعارات الهاتف</button></div><div class="vz-list" data-nlist></div>`;document.body.appendChild(panel);
    const list=panel.querySelector('[data-nlist]');
    const fmt=d=>new Date(d).toLocaleString('ar-LY',{dateStyle:'medium',timeStyle:'short'});
    const render=rows=>{badge.hidden=!rows.some(x=>!x.read_at);const unread=rows.filter(x=>!x.read_at).length;badge.textContent=unread>99?'99+':unread;list.innerHTML=rows.length?rows.map(x=>`<div class="vz-item ${x.read_at?'':'unread'}" data-id="${x.id}"><strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.body)}</span><small>${fmt(x.created_at)}</small></div>`).join(''):'<div class="vz-empty">ما فيش إشعارات حتى الآن.</div>';list.querySelectorAll('[data-id]').forEach(el=>el.onclick=async()=>{await client.from('notifications').update({read_at:new Date().toISOString()}).eq('id',el.dataset.id).eq('admin_user_id',session.user.id);load()})};
    const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
    const load=async()=>{const {data}=await client.from('notifications').select('id,title,body,read_at,created_at,order_id').eq('admin_user_id',session.user.id).order('created_at',{ascending:false}).limit(100);render(data||[])}; const open=()=>{panel.classList.add('open');shade.classList.add('open');load()}; const close=()=>{panel.classList.remove('open');shade.classList.remove('open')}; btn.onclick=open; shade.onclick=close;panel.querySelector('[data-nclose]').onclick=close;
    panel.querySelector('[data-enable]').onclick=async()=>{try{if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('إشعارات الهاتف غير مدعومة هنا');const perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('تم رفض إذن الإشعارات');const reg=await navigator.serviceWorker.ready;const cfg=await fetch('/api/push-config',{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json());if(!cfg.publicKey)throw new Error('تعذر تجهيز إشعارات الهاتف');let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(cfg.publicKey)});const r=await fetch('/api/push-subscribe',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(sub.toJSON())});if(!r.ok)throw new Error('تعذر حفظ إعداد الإشعارات');panel.querySelector('[data-enable]').textContent='إشعارات الهاتف مفعّلة ✓'}catch(e){alert(e.message||'تعذر تفعيل الإشعارات')}};
    const base64ToBytes=b64=>{const pad='='.repeat((4-b64.length%4)%4),raw=atob((b64+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))};
    client.channel('veronza-notifications').on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`admin_user_id=eq.${session.user.id}`},payload=>{load();try{new Audio('data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=').play()}catch(_){}}).subscribe();
    load();
  };
  wait();
})();
